platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'SysBoilerplateRN' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  # Pods for SysBoilerplateRN

  target 'SysBoilerplateRNTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SysBoilerplateRN-tvOS' do
  # Pods for SysBoilerplateRN-tvOS

  target 'SysBoilerplateRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
